# Generated by Django 3.1.3 on 2020-11-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201015_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=25)),
                ('modelo', models.CharField(max_length=25)),
                ('codigo', models.CharField(max_length=25)),
                ('descripcion', models.TextField(max_length=1000)),
                ('serie', models.CharField(max_length=25)),
                ('estado', models.CharField(choices=[('I', 'Ingresado'), ('P', 'En Proceso'), ('R', 'Reparado'), ('E', 'Entregado')], default='I', max_length=1)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
